app = "datomic-console-@SLUG@"
primary_region = "scl"

[experimental]
cmd = ["make", "run-console"]

[http_service]
internal_port = 8999
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
