app = "datomic-console-@SLUG@"
primary_region = "scl"

[experimental]
cmd = ["make", "run-console"]

[checks]
[checks.datomic-console-@SLUG@]
port = 8999
type = "tcp"
grace_period = "10s"
interval = "15s"
timeout = "5s"
