#!/usr/bin/env bash
# -*- coding: utf-8; mode: sh -*-
set -euo pipefail
IFS=$'\n\t'

THIS="$(readlink -f "$0")"
readonly THIS

function on_exit() {
    errcode="$1"
}

trap 'on_exit $?' EXIT

function on_error() {
    errcode=$1
    linenum=$2
    echo 1>&2 "[ERROR] $THIS: errcode: $errcode linenum: $linenum"
}

trap 'on_error $? $LINENO' ERR

if ! command -v podman > /dev/null; then
    # shellcheck disable=SC2016
    echo 1>&2 'The command `podman` does not exist in PATH'
    exit 1
fi

if [[ -z ${FLY_ACCESS_TOKEN:-} ]]; then
    # shellcheck disable=SC2016
    echo 1>&2 'The environment variable `FLY_ACCESS_TOKEN` is undefined'
    exit 1
fi

IFS=$' ' PODMAN_EXTRA_RUN_ARGS="${PODMAN_EXTRA_RUN_ARGS:-}"

if test -t 0; then
    IFS=$' ' PODMAN_EXTRA_RUN_ARGS="-it $PODMAN_EXTRA_RUN_ARGS"
fi

readonly PODMAN_EXTRA_RUN_ARGS

FLY_IMAGE=docker.io/flyio/flyctl:v0.2.79
readonly FLY_IMAGE

podman pull -q $FLY_IMAGE
podman run --rm $PODMAN_EXTRA_RUN_ARGS                                          \
    -e FLY_NO_UPDATE_CHECK=1                                                    \
    -e HOME=/tmp                                                                \
    -v "$PWD":/mnt/workdir                                                      \
    -v /var/run/docker.sock:/var/run/docker.sock:ro                             \
    -w /mnt/workdir                                                             \
    "$FLY_IMAGE"                                                                \
    -t "$FLY_ACCESS_TOKEN"                                                      \
    "$@"
